title: iScript
description: Turn the scripts you love into focused language learning with iScript.
theme: jekyll-theme-slate
baseurl: ""
url: "https://iscript.dev"
markdown: kramdown
show_downloads: false

exclude:
  - "*-legacy.md"

