const xlsx = require('xlsx');

// Global arrays to hold data
let basic_korean = [];
let business_korean = [];
let travel_korean = [];
let verbs_100 = []; // This one we might assume is already full or handle separately, focusing on sentences for now.

// --- Helper Function to Append Data ---
function addData(category, data) {
    if (category === 'basic') basic_korean.push(...data);
    if (category === 'business') business_korean.push(...data);
    if (category === 'travel') travel_korean.push(...data);
}

// --- PART 1: 1~30 ---
addData('basic', [
    { Korean: "안녕하세요.", English: "Hello." },
    { Korean: "처음 뵙겠습니다.", English: "Nice to meet you." },
    { Korean: "오랜만이에요.", English: "Long time no see." },
    { Korean: "어떻게 지내세요?", English: "How are you doing?" },
    { Korean: "잘 지내요.", English: "I'm doing well." },
    { Korean: "만나서 반가워요.", English: "Glad to meet you." },
    { Korean: "감사합니다.", English: "Thank you." },
    { Korean: "천만에요.", English: "You're welcome." },
    { Korean: "죄송합니다.", English: "I'm sorry." },
    { Korean: "괜찮아요.", English: "It's okay." },
    { Korean: "실례합니다.", English: "Excuse me." },
    { Korean: "잠시만요.", English: "Just a moment." },
    { Korean: "저기요.", English: "Excuse me (to call someone)." },
    { Korean: "네.", English: "Yes." },
    { Korean: "아니요.", English: "No." },
    { Korean: "아마도요.", English: "Maybe." },
    { Korean: "물론이죠.", English: "Of course." },
    { Korean: "부탁합니다.", English: "Please." },
    { Korean: "도와주세요.", English: "Help me." },
    { Korean: "이해했어요.", English: "I understand." },
    { Korean: "이해 못 했어요.", English: "I don't understand." },
    { Korean: "다시 말해주세요.", English: "Please say it again." },
    { Korean: "천천히 말해주세요.", English: "Please speak slowly." },
    { Korean: "영어 할 수 있어요?", English: "Can you speak English?" },
    { Korean: "한국어 조금 해요.", English: "I speak a little Korean." },
    { Korean: "이름이 뭐예요?", English: "What is your name?" },
    { Korean: "제 이름은 ...입니다.", English: "My name is ..." },
    { Korean: "어디서 오셨어요?", English: "Where are you from?" },
    { Korean: "저는 미국에서 왔어요.", English: "I am from the USA." },
    { Korean: "몇 살이세요?", English: "How old are you?" },
]);

addData('business', [
    { Korean: "안녕하십니까.", English: "Greetings (Formal)." },
    { Korean: "수고하셨습니다.", English: "Good job today. / Thank you for your effort." },
    { Korean: "회의 시작하겠습니다.", English: "Let's start the meeting." },
    { Korean: "의견 있으신가요?", English: "Do you have any opinions?" },
    { Korean: "결재 부탁드립니다.", English: "Please approve this." },
    { Korean: "보고서 제출했습니다.", English: "I submitted the report." },
    { Korean: "이메일 확인 부탁드립니다.", English: "Please check your email." },
    { Korean: "오늘 회식 있나요?", English: "Do we have a team dinner today?" },
    { Korean: "야근해야 할 것 같습니다.", English: "I think I have to work overtime." },
    { Korean: "출장 다녀오겠습니다.", English: "I will go on a business trip." },
    { Korean: "죄송하지만, 잠시 통화 가능하신가요?", English: "Sorry, can you talk for a moment?" },
    { Korean: "담당자 연결해 드리겠습니다.", English: "I will connect you to the person in charge." },
    { Korean: "일정 확인해보겠습니다.", English: "I will check the schedule." },
    { Korean: "협조해주셔서 감사합니다.", English: "Thank you for your cooperation." },
    { Korean: "마감 기한은 언제인가요?", English: "When is the deadline?" },
    { Korean: "문제 없습니다.", English: "No problem." },
    { Korean: "검토 후 연락드리겠습니다.", English: "I will contact you after review." },
    { Korean: "명함 한 장 주시겠습니까?", English: "Could you give me your business card?" },
    { Korean: "승진 축하드립니다.", English: "Congratulations on your promotion." },
    { Korean: "휴가 잘 다녀오세요.", English: "Have a nice vacation." },
    { Korean: "퇴근하겠습니다.", English: "I'm leaving work now." },
    { Korean: "내일 뵙겠습니다.", English: "See you tomorrow." },
    { Korean: "양해 부탁드립니다.", English: "I ask for your understanding." },
    { Korean: "최선을 다하겠습니다.", English: "I will do my best." },
    { Korean: "좋은 결과 기대하겠습니다.", English: "I look forward to good results." },
    { Korean: "거래처 미팅이 있습니다.", English: "I have a meeting with a client." },
    { Korean: "견적서 보내주세요.", English: "Please send me the quotation." },
    { Korean: "계약이 성사되었습니다.", English: "The contract has been signed." },
    { Korean: "프로젝트 진행 상황 보고해주세요.", English: "Please report the project progress." },
    { Korean: "수고하세요.", English: "Keep up the good work. (Formal greeting)" },
]);

addData('travel', [
    { Korean: "여권 보여주세요.", English: "Please show me your passport." },
    { Korean: "체크인 부탁합니다.", English: "Check-in, please." },
    { Korean: "예약했습니다.", English: "I made a reservation." },
    { Korean: "방이 추워요.", English: "The room is cold." },
    { Korean: "와이파이 비밀번호가 뭐예요?", English: "What is the Wi-Fi password?" },
    { Korean: "여기 맛집 추천해주세요.", English: "Global restaurant recommendation please." },
    { Korean: "메뉴판 주세요.", English: "Menu please." },
    { Korean: "물 좀 주세요.", English: "Water please." },
    { Korean: "계산서 주세요.", English: "Bill please." },
    { Korean: "여기서 제일 인기 있는 게 뭐예요?", English: "What is the most popular dish here?" },
    { Korean: "덜 맵게 해주세요.", English: "Make it less spicy please." },
    { Korean: "이거 환불 되나요?", English: "Can I get a refund for this?" },
    { Korean: "깎아주세요.", English: "Please give me a discount." },
    { Korean: "입어봐도 되나요?", English: "Can I try this on?" },
    { Korean: "지하철 역이 어디예요?", English: "Where is the subway station?" },
    { Korean: "택시 불러주세요.", English: "Please call a taxi." },
    { Korean: "서울역으로 가주세요.", English: "To Seoul Station, please." },
    { Korean: "얼마나 걸려요?", English: "How long does it take?" },
    { Korean: "사진 좀 찍어주실래요?", English: "Could you take a picture for us?" },
    { Korean: "길을 잃었어요.", English: "I'm lost." },
    { Korean: "도와주세요.", English: "Help me." },
    { Korean: "경찰을 불러주세요.", English: "Please call the police." },
    { Korean: "병원에 가고 싶어요.", English: "I want to go to the hospital." },
    { Korean: "약국이 어디 있나요?", English: "Where is the pharmacy?" },
    { Korean: "화장실이 급해요.", English: "I need to use the bathroom urgently." },
    { Korean: "가방을 잃어버렸어요.", English: "I lost my bag." },
    { Korean: "지갑을 잃어버렸어요.", English: "I lost my wallet." },
    { Korean: "여권을 잃어버렸어요.", English: "I lost my passport." },
    { Korean: "대사관이 어디예요?", English: "Where is the embassy?" },
    { Korean: "환전소는 어디예요?", English: "Where is the currency exchange?" },
]);

// --- PART 2: 31~60 ---
addData('basic', [
    { Korean: "직업이 뭐예요?", English: "What is your job?" },
    { Korean: "학생이에요.", English: "I am a student." },
    { Korean: "회사원이에요.", English: "I am an office worker." },
    { Korean: "취미가 뭐예요?", English: "What are your hobbies?" },
    { Korean: "저는 영화 보는 걸 좋아해요.", English: "I like watching movies." },
    { Korean: "오늘 날씨가 좋네요.", English: "The weather is good today." },
    { Korean: "비가 오네요.", English: "It's raining." },
    { Korean: "추워요.", English: "It's cold." },
    { Korean: "더워요.", English: "It's hot." },
    { Korean: "지금 몇 시예요?", English: "What time is it now?" },
    { Korean: "배고파요.", English: "I'm hungry." },
    { Korean: "배불러요.", English: "I'm full." },
    { Korean: "목 말라요.", English: "I'm thirsty." },
    { Korean: "맛있어요.", English: "It's delicious." },
    { Korean: "맛없어요.", English: "It's not delicious." },
    { Korean: "잘 먹겠습니다.", English: "I will eat well (Bon appétit)." },
    { Korean: "잘 먹었습니다.", English: "I ate well (Thank you for the meal)." },
    { Korean: "메뉴판 주세요.", English: "Menu please." },
    { Korean: "이거 주세요.", English: "This one please." },
    { Korean: "물 좀 주세요.", English: "Water please." },
    { Korean: "계산해 주세요.", English: "Check please." },
    { Korean: "영수증 주세요.", English: "Receipt please." },
    { Korean: "화장실이 어디예요?", English: "Where is the bathroom?" },
    { Korean: "입구는 어디예요?", English: "Where is the entrance?" },
    { Korean: "출구는 어디예요?", English: "Where is the exit?" },
    { Korean: "왼쪽으로 가세요.", English: "Go left." },
    { Korean: "오른쪽으로 가세요.", English: "Go right." },
    { Korean: "쭉 가세요.", English: "Go straight." },
    { Korean: "여기서 세워주세요.", English: "Stop here please." },
    { Korean: "얼마예요?", English: "How much is it?" },
]);

addData('business', [
    { Korean: "자료 준비되었습니다.", English: "The materials are ready." },
    { Korean: "언제 시간 되시나요?", English: "When are you available?" },
    { Korean: "점심 식사 하셨습니까?", English: "Have you had lunch?" },
    { Korean: "커피 한 잔 하시겠습니까?", English: "Would you like a cup of coffee?" },
    { Korean: "잠시 자리 비우셨습니다.", English: "He/She is away from the desk for a moment." },
    { Korean: "메모 남겨드릴까요?", English: "Shall I leave a message?" },
    { Korean: "팩스로 보내주세요.", English: "Please send it by fax." },
    { Korean: "프레젠테이션 준비 완료했습니다.", English: "Presentation preparation is complete." },
    { Korean: "예산안 검토 부탁드립니다.", English: "Please review the budget proposal." },
    { Korean: "다음 주 일정 잡겠습니다.", English: "I will schedule it for next week." },
    { Korean: "출근했습니다.", English: "I have arrived at work." },
    { Korean: "병가 내겠습니다.", English: "I will take a sick leave." },
    { Korean: "연차 쓰겠습니다.", English: "I will use my annual leave." },
    { Korean: "급한 일입니까?", English: "Is it urgent?" },
    { Korean: "우선순위가 어떻게 되나요?", English: "What is the priority?" },
    { Korean: "피드백 부탁드립니다.", English: "Please give me feedback." },
    { Korean: "수정해서 다시 보내겠습니다.", English: "I will revise and resend it." },
    { Korean: "성공적인 프로젝트였습니다.", English: "It was a successful project." },
    { Korean: "함께 일해서 즐거웠습니다.", English: "It was a pleasure working with you." },
    { Korean: "앞으로도 잘 부탁드립니다.", English: "I look forward to working with you." },
    { Korean: "안녕하십니까.", English: "Hello (formal)." },
    { Korean: "처음 뵙겠습니다.", English: "Nice to meet you (first time)." },
    { Korean: "잘 부탁드립니다.", English: "I look forward to your cooperation." },
    { Korean: "오랜만입니다.", English: "Long time no see (formal)." },
    { Korean: "그동안 잘 지내셨습니까?", English: "How have you been (formal)?" },
    { Korean: "소개해 드리겠습니다.", English: "Let me introduce you." },
    { Korean: "이쪽은 제 동료입니다.", English: "This is my colleague." },
    { Korean: "명함 교환하시죠.", English: "Let's exchange business cards." },
    { Korean: "연락처를 알 수 있을까요?", English: "May I have your contact information?" },
    { Korean: "이메일 주소 알려주세요.", English: "Please tell me the email address." },
]);

addData('travel', [
    { Korean: "ATM이 어디예요?", English: "Where is the ATM?" },
    { Korean: "신용카드 되나요?", English: "Do you accept credit cards?" },
    { Korean: "현금만 받나요?", English: "Do you only accept cash?" },
    { Korean: "잔돈은 괜찮아요.", English: "Keep the change." },
    { Korean: "팁 포함인가요?", English: "Is tip included?" },
    { Korean: "포장해 주세요.", English: "To-go, please." },
    { Korean: "따로 계산할게요.", English: "We will pay separately." },
    { Korean: "젓가락 주세요.", English: "Chopsticks please." },
    { Korean: "포크 주세요.", English: "Fork please." },
    { Korean: "냅킨 주세요.", English: "Napkin please." },
    { Korean: "리필 되나요?", English: "Is refill free?" },
    { Korean: "너무 맛있어요.", English: "It's very delicious." },
    { Korean: "짜요.", English: "It's salty." },
    { Korean: "싱거워요.", English: "It's bland." },
    { Korean: "달아요.", English: "It's sweet." },
    { Korean: "매워요.", English: "It's spicy." },
    { Korean: "셔요.", English: "It's sour." },
    { Korean: "써요.", English: "It's bitter." },
    { Korean: "알러지가 있어요.", English: "I have an allergy." },
    { Korean: "고기는 빼주세요.", English: "Please remove meat." },
    { Korean: "채식주의자용 메뉴 있나요?", English: "Do you have vegetarian menu?" },
    { Korean: "돼지고기 못 먹어요.", English: "I can't eat pork." },
    { Korean: "소고기 못 먹어요.", English: "I can't eat beef." },
    { Korean: "해산물 못 먹어요.", English: "I can't eat seafood." },
    { Korean: "견과류 알러지 있어요.", English: "I have nut allergy." },
    { Korean: "빈 방 있나요?", English: "Do you have vacant rooms?" },
    { Korean: "1박에 얼마예요?", English: "How much per night?" },
    { Korean: "조식 포함인가요?", English: "Is breakfast included?" },
    { Korean: "체크아웃 시간은 언제예요?", English: "When is check-out time?" },
    { Korean: "짐 맡길 수 있나요?", English: "Can I leave my luggage?" },
]);

// --- PART 3: 61~90 ---
addData('basic', [
    { Korean: "너무 비싸요.", English: "It's too expensive." },
    { Korean: "깎아주세요.", English: "Please give me a discount." },
    { Korean: "카드로 계산할게요.", English: "I will pay by card." },
    { Korean: "현금으로 계산할게요.", English: "I will pay by cash." },
    { Korean: "환불해 주세요.", English: "Please refund it." },
    { Korean: "교환해 주세요.", English: "Please exchange it." },
    { Korean: "이거 입어봐도 되나요?", English: "Can I try this on?" },
    { Korean: "사이즈가 안 맞아요.", English: "The size doesn't fit." },
    { Korean: "더 큰 사이즈 있어요?", English: "Do you have a bigger size?" },
    { Korean: "더 작은 사이즈 있어요?", English: "Do you have a smaller size?" },
    { Korean: "어떤 색깔 좋아해요?", English: "What color do you like?" },
    { Korean: "파란색 좋아해요.", English: "I like blue." },
    { Korean: "생일 축하해요.", English: "Happy birthday." },
    { Korean: "축하해요!", English: "Congratulations!" },
    { Korean: "새해 복 많이 받으세요.", English: "Happy New Year." },
    { Korean: "메리 크리스마스.", English: "Merry Christmas." },
    { Korean: "사랑해요.", English: "I love you." },
    { Korean: "보고 싶어요.", English: "I miss you." },
    { Korean: "좋아해요.", English: "I like you." },
    { Korean: "결혼해 줄래?", English: "Will you marry me?" },
    { Korean: "헤어지자.", English: "Let's break up." },
    { Korean: "정말요?", English: "Really?" },
    { Korean: "거짓말 하지 마세요.", English: "Don't lie." },
    { Korean: "약속해요.", English: "I promise." },
    { Korean: "비밀이에요.", English: "It's a secret." },
    { Korean: "걱정하지 마세요.", English: "Don't worry." },
    { Korean: "힘내세요.", English: "Cheer up." },
    { Korean: "수고하셨습니다.", English: "Good job." },
    { Korean: "피곤해요.", English: "I'm tired." },
    { Korean: "아파요.", English: "I'm sick/It hurts." },
]);

addData('business', [
    { Korean: "전화 연결해 드리겠습니다.", English: "I'll connect you." },
    { Korean: "부재중입니다.", English: "He/She is currently unavailable/out of office." },
    { Korean: "나중에 다시 걸겠습니다.", English: "I'll call back later." },
    { Korean: "메시지를 남기시겠습니까?", English: "Would you like to leave a message?" },
    { Korean: "잘 안 들립니다.", English: "I can't hear you well." },
    { Korean: "좀 더 크게 말씀해 주세요.", English: "Please speak up a little." },
    { Korean: "끊겠습니다.", English: "I'm hanging up." },
    { Korean: "회의실을 예약했습니다.", English: "I reserved the meeting room." },
    { Korean: "빔 프로젝터가 필요합니다.", English: "I need a beam projector." },
    { Korean: "자료를 복사해 주세요.", English: "Please copy the materials." },
    { Korean: "회의록을 작성하겠습니다.", English: "I will write the minutes." },
    { Korean: "안건이 무엇입니까?", English: "What is the agenda?" },
    { Korean: "결론을 내립시다.", English: "Let's come to a conclusion." },
    { Korean: "다음 회의는 언제입니까?", English: "When is the next meeting?" },
    { Korean: "참석해 주셔서 감사합니다.", English: "Thank you for attending." },
    { Korean: "추가 질문 있습니까?", English: "Any further questions?" },
    { Korean: "시간이 부족합니다.", English: "We are running out of time." },
    { Korean: "잠시 쉬겠습니다.", English: "Let's take a break." },
    { Korean: "이만 마치겠습니다.", English: "We will wrap up now." },
    { Korean: "보고서를 검토했습니다.", English: "I reviewed the report." },
    { Korean: "수정이 필요합니다.", English: "It needs revision." },
    { Korean: "오타가 있습니다.", English: "There is a typo." },
    { Korean: "내용이 부족합니다.", English: "The content is insufficient." },
    { Korean: "다시 작성해 주세요.", English: "Please rewrite it." },
    { Korean: "잘 작성되었습니다.", English: "It is well written." },
    { Korean: "승인 받았습니다.", English: "It has been approved." },
    { Korean: "반려되었습니다.", English: "It has been rejected." },
    { Korean: "기한을 연장할 수 있나요?", English: "Can we extend the deadline?" },
    { Korean: "최대한 빨리 처리하겠습니다.", English: "I will process it as soon as possible." },
    { Korean: "문제가 해결되었습니다.", English: "The problem has been resolved." },
]);

addData('travel', [
    { Korean: "택시 잡아주세요.", English: "Please catch a taxi." },
    { Korean: "공항 버스 어디서 타요?", English: "Where can I take the airport bus?" },
    { Korean: "기차역이 어디예요?", English: "Where is the train station?" },
    { Korean: "버스 정류장이 어디예요?", English: "Where is the bus stop?" },
    { Korean: "이 버스 시청 가나요?", English: "Does this bus go to City Hall?" },
    { Korean: "내려주세요.", English: "Please let me off." },
    { Korean: "환승해야 하나요?", English: "Do I need to transfer?" },
    { Korean: "몇 호선 타야 해요?", English: "Which line should I take?" },
    { Korean: "오른쪽.", English: "Right." },
    { Korean: "왼쪽.", English: "Left." },
    { Korean: "직진.", English: "Straight." },
    { Korean: "건너편.", English: "Across the street." },
    { Korean: "근처에 편의점 있나요?", English: "Is there a convenience store nearby?" },
    { Korean: "슈퍼마켓 어디예요?", English: "Where is the supermarket?" },
    { Korean: "기념품 가게 어디예요?", English: "Where is the souvenir shop?" },
    { Korean: "면세점 어디예요?", English: "Where is the duty-free shop?" },
    { Korean: "세일 중인가요?", English: "Is it on sale?" },
    { Korean: "영업시간이 어떻게 되나요?", English: "What are the business hours?" },
    { Korean: "문 닫았나요?", English: "Is it closed?" },
    { Korean: "언제 여나요?", English: "When does it open?" },
    { Korean: "입장료 얼마예요?", English: "How much is the admission fee?" },
    { Korean: "사진 찍어도 되나요?", English: "Can I take pictures?" },
    { Korean: "플래시 터트려도 되나요?", English: "Can I use flash?" },
    { Korean: "한국어 가이드 있나요?", English: "Is there a Korean guide?" },
    { Korean: "오디오 가이드 있나요?", English: "Is there an audio guide?" },
    { Korean: "지도 있나요?", English: "Do you have a map?" },
    { Korean: "추천 코스 있나요?", English: "Any recommended course?" },
    { Korean: "걸어서 갈 수 있나요?", English: "Can I go on foot?" },
    { Korean: "너무 멀어요.", English: "It's too far." },
    { Korean: "가까워요.", English: "It's close." },
]);

// --- PART 4: 91~100 ---
addData('basic', [
    { Korean: "병원에 가야 해요.", English: "I need to go to the hospital." },
    { Korean: "약국이 어디예요?", English: "Where is the pharmacy?" },
    { Korean: "머리가 아파요.", English: "I have a headache." },
    { Korean: "배가 아파요.", English: "I have a stomachache." },
    { Korean: "감기 걸렸어요.", English: "I caught a cold." },
    { Korean: "조심하세요.", English: "Be careful." },
    { Korean: "위험해요.", English: "It's dangerous." },
    { Korean: "도와드릴까요?", English: "Can I help you?" },
    { Korean: "무슨 일이에요?", English: "What happened?" },
    { Korean: "재미있어요.", English: "It's fun." }
]);

addData('business', [
    { Korean: "컴퓨터가 고장났습니다.", English: "The computer is broken." },
    { Korean: "인터넷이 안 됩니다.", English: "The internet is not working." },
    { Korean: "비밀번호를 잊어버렸습니다.", English: "I forgot my password." },
    { Korean: "로그인이 안 됩니다.", English: "I can't log in." },
    { Korean: "파일이 안 열립니다.", English: "The file won't open." },
    { Korean: "바이러스에 감염되었습니다.", English: "It is infected with a virus." },
    { Korean: "백업을 해야 합니다.", English: "We need to backup." },
    { Korean: "소프트웨어를 업데이트하세요.", English: "Please update the software." },
    { Korean: "재부팅해 보세요.", English: "Try rebooting." },
    { Korean: "IT 지원팀에 연락하세요.", English: "Contact IT support." },
]);

addData('travel', [
    { Korean: "전화기 빌릴 수 있을까요?", English: "Can I borrow a phone?" },
    { Korean: "충전기 빌릴 수 있을까요?", English: "Can I borrow a charger?" },
    { Korean: "콘센트 어디 있나요?", English: "Where is the outlet?" },
    { Korean: "비상구는 어디인가요?", English: "Where is the emergency exit?" },
    { Korean: "소화기는 어디 있나요?", English: "Where is the fire extinguisher?" },
    { Korean: "구급차 불러주세요.", English: "Call an ambulance." },
    { Korean: "경찰 불러주세요.", English: "Call the police." },
    { Korean: "불이야!", English: "Fire!" },
    { Korean: "도둑이야!", English: "Thief!" },
    { Korean: "도와주세요!", English: "Help!" },
]);

// --- Create Files ---
function createExcel(data, filename) {
    const ws = xlsx.utils.json_to_sheet(data);
    const wb = xlsx.utils.book_new();
    xlsx.utils.book_append_sheet(wb, ws, "Sheet1");
    // Ensure the output file is written to the assets/files/samples directory
    xlsx.writeFile(wb, `../assets/files/samples/${filename}`);
    console.log(`Created ${filename} with ${data.length} rows`);
}

createExcel(basic_korean, "basic_korean.xlsx");
createExcel(business_korean, "business_korean.xlsx");
createExcel(travel_korean, "travel_korean.xlsx");
