const xlsx = require('xlsx');

// 1. [Basic] Daily Life Expressions (30 sentences)
const basic_korean = [
    { Korean: "안녕하세요!", English: "Hello!" },
    { Korean: "반가워요.", English: "Nice to meet you." },
    { Korean: "감사합니다.", English: "Thank you." },
    { Korean: "죄송합니다.", English: "I'm sorry." },
    { Korean: "얼마예요?", English: "How much is this?" },
    { Korean: "맛있어요.", English: "It's delicious." },
    { Korean: "사랑해요.", English: "I love you." },
    { Korean: "잠시만요.", English: "Just a moment." },
    { Korean: "화이팅!", English: "Cheer up! / Good luck!" },
    { Korean: "안녕히 가세요.", English: "Goodbye. (to someone leaving)" },
    { Korean: "안녕히 계세요.", English: "Goodbye. (to someone staying)" },
    { Korean: "잘 자요.", English: "Good night." },
    { Korean: "배가 고파요.", English: "I'm hungry." },
    { Korean: "어디예요?", English: "Where are you?" },
    { Korean: "화장실 어디예요?", English: "Where is the bathroom?" },
    { Korean: "도와주세요.", English: "Help me." },
    { Korean: "괜찮아요.", English: "I'm okay." },
    { Korean: "축하해요!", English: "Congratulations!" },
    { Korean: "생일 축하해요.", English: "Happy birthday." },
    { Korean: "이름이 뭐예요?", English: "What is your name?" },
    { Korean: "제 이름은 ...입니다.", English: "My name is ..." },
    { Korean: "한국 사람이에요?", English: "Are you Korean?" },
    { Korean: "영어 할 수 있어요?", English: "Can you speak English?" },
    { Korean: "좋아요.", English: "I like it. / Good." },
    { Korean: "싫어요.", English: "I don't like it." },
    { Korean: "진짜요?", English: "Really?" },
    { Korean: "몰라요.", English: "I don't know." },
    { Korean: "알아요.", English: "I know." },
    { Korean: "천만에요.", English: "You're welcome." },
    { Korean: "다음에 봐요.", English: "See you next time." }
];

// 2. [Intermediate] Office Business Talk (50 sentences)
const business_korean = [
    { Korean: "안녕하십니까.", English: "Greetings (Formal)." },
    { Korean: "수고하셨습니다.", English: "Good job today. / Thank you for your effort." },
    { Korean: "회의 시작하겠습니다.", English: "Let's start the meeting." },
    { Korean: "의견 있으신가요?", English: "Do you have any opinions?" },
    { Korean: "결재 부탁드립니다.", English: "Please approve this." },
    { Korean: "보고서 제출했습니다.", English: "I submitted the report." },
    { Korean: "이메일 확인 부탁드립니다.", English: "Please check your email." },
    { Korean: "오늘 회식 있나요?", English: "Do we have a team dinner today?" },
    { Korean: "야근해야 할 것 같습니다.", English: "I think I have to work overtime." },
    { Korean: "출장 다녀오겠습니다.", English: "I will go on a business trip." },
    { Korean: "죄송하지만, 잠시 통화 가능하신가요?", English: "Sorry, can you talk for a moment?" },
    { Korean: "담당자 연결해 드리겠습니다.", English: "I will connect you to the person in charge." },
    { Korean: "일정 확인해보겠습니다.", English: "I will check the schedule." },
    { Korean: "협조해주셔서 감사합니다.", English: "Thank you for your cooperation." },
    { Korean: "마감 기한은 언제인가요?", English: "When is the deadline?" },
    { Korean: "문제 없습니다.", English: "No problem." },
    { Korean: "검토 후 연락드리겠습니다.", English: "I will contact you after review." },
    { Korean: "명함 한 장 주시겠습니까?", English: "Could you give me your business card?" },
    { Korean: "승진 축하드립니다.", English: "Congratulations on your promotion." },
    { Korean: "휴가 잘 다녀오세요.", English: "Have a nice vacation." },
    { Korean: "퇴근하겠습니다.", English: "I'm leaving work now." },
    { Korean: "내일 뵙겠습니다.", English: "See you tomorrow." },
    { Korean: "양해 부탁드립니다.", English: "I ask for your understanding." },
    { Korean: "최선을 다하겠습니다.", English: "I will do my best." },
    { Korean: "좋은 결과 기대하겠습니다.", English: "I look forward to good results." },
    { Korean: "거래처 미팅이 있습니다.", English: "I have a meeting with a client." },
    { Korean: "견적서 보내주세요.", English: "Please send me the quotation." },
    { Korean: "계약이 성사되었습니다.", English: "The contract has been signed." },
    { Korean: "프로젝트 진행 상황 보고해주세요.", English: "Please report the project progress." },
    { Korean: "수고하세요.", English: "Keep up the good work. (Formal greeting)" },
    { Korean: "자료 준비되었습니다.", English: "The materials are ready." },
    { Korean: "언제 시간 되시나요?", English: "When are you available?" },
    { Korean: "점심 식사 하셨습니까?", English: "Have you had lunch?" },
    { Korean: "커피 한 잔 하시겠습니까?", English: "Would you like a cup of coffee?" },
    { Korean: "잠시 자리 비우셨습니다.", English: "He/She is away from the desk for a moment." },
    { Korean: "메모 남겨드릴까요?", English: "Shall I leave a message?" },
    { Korean: "팩스로 보내주세요.", English: "Please send it by fax." },
    { Korean: "프레젠테이션 준비 완료했습니다.", English: "Presentation preparation is complete." },
    { Korean: "예산안 검토 부탁드립니다.", English: "Please review the budget proposal." },
    { Korean: "다음 주 일정 잡겠습니다.", English: "I will schedule it for next week." },
    { Korean: "출근했습니다.", English: "I have arrived at work." },
    { Korean: "병가 내겠습니다.", English: "I will take a sick leave." },
    { Korean: "연차 쓰겠습니다.", English: "I will use my annual leave." },
    { Korean: "급한 일입니까?", English: "Is it urgent?" },
    { Korean: "우선순위가 어떻게 되나요?", English: "What is the priority?" },
    { Korean: "피드백 부탁드립니다.", English: "Please give me feedback." },
    { Korean: "수정해서 다시 보내겠습니다.", English: "I will revise and resend it." },
    { Korean: "성공적인 프로젝트였습니다.", English: "It was a successful project." },
    { Korean: "함께 일해서 즐거웠습니다.", English: "It was a pleasure working with you." },
    { Korean: "앞으로도 잘 부탁드립니다.", English: "I look forward to working with you." }
];

// 3. [Beginner] Top 100 Essential Verbs (100 verbs, no examples)
const verbs_100 = [
    { Korean: "가다", English: "to go" },
    { Korean: "오다", English: "to come" },
    { Korean: "먹다", English: "to eat" },
    { Korean: "마시다", English: "to drink" },
    { Korean: "보다", English: "to see/watch" },
    { Korean: "듣다", English: "to hear/listen" },
    { Korean: "말하다", English: "to speak" },
    { Korean: "하다", English: "to do" },
    { Korean: "자다", English: "to sleep" },
    { Korean: "일어나다", English: "to wake up" },
    { Korean: "사다", English: "to buy" },
    { Korean: "팔다", English: "to sell" },
    { Korean: "주다", English: "to give" },
    { Korean: "받다", English: "to receive" },
    { Korean: "읽다", English: "to read" },
    { Korean: "쓰다", English: "to write/use" },
    { Korean: "배우다", English: "to learn" },
    { Korean: "가르치다", English: "to teach" },
    { Korean: "일하다", English: "to work" },
    { Korean: "쉬다", English: "to rest" },
    { Korean: "놀다", English: "to play" },
    { Korean: "만나다", English: "to meet" },
    { Korean: "헤어지다", English: "to break up" },
    { Korean: "웃다", English: "to laugh" },
    { Korean: "울다", English: "to cry" },
    { Korean: "사랑하다", English: "to love" },
    { Korean: "좋아하다", English: "to like" },
    { Korean: "싫어하다", English: "to dislike/hate" },
    { Korean: "살다", English: "to live" },
    { Korean: "죽다", English: "to die" },
    { Korean: "열다", English: "to open" },
    { Korean: "닫다", English: "to close" },
    { Korean: "입다", English: "to wear" },
    { Korean: "벗다", English: "to take off" },
    { Korean: "신다", English: "to wear (shoes/socks)" },
    { Korean: "타다", English: "to ride" },
    { Korean: "내리다", English: "to get off" },
    { Korean: "걷다", English: "to walk" },
    { Korean: "뛰다", English: "to run" },
    { Korean: "앉다", English: "to sit" },
    { Korean: "서다", English: "to stand" },
    { Korean: "알다", English: "to know" },
    { Korean: "모르다", English: "to not know" },
    { Korean: "생각하다", English: "to think" },
    { Korean: "기억하다", English: "to remember" },
    { Korean: "잊다", English: "to forget" },
    { Korean: "느끼다", English: "to feel" },
    { Korean: "보내다", English: "to send" },
    { Korean: "빌리다", English: "to borrow" },
    { Korean: "돌려주다", English: "to return" },
    { Korean: "돕다", English: "to help" },
    { Korean: "필요하다", English: "to need" },
    { Korean: "찾다", English: "to find/look for" },
    { Korean: "잃어버리다", English: "to lose" },
    { Korean: "시작하다", English: "to start" },
    { Korean: "끝나다", English: "to end" },
    { Korean: "기다리다", English: "to wait" },
    { Korean: "준비하다", English: "to prepare" },
    { Korean: "약속하다", English: "to promise" },
    { Korean: "거짓말하다", English: "to lie" },
    { Korean: "고백하다", English: "to confess" },
    { Korean: "결혼하다", English: "to marry" },
    { Korean: "이혼하다", English: "to divorce" },
    { Korean: "태어나다", English: "to be born" },
    { Korean: "자라다", English: "to grow up" },
    { Korean: "이기다", English: "to win" },
    { Korean: "지다", English: "to lose (game)" },
    { Korean: "싸우다", English: "to fight" },
    { Korean: "화내다", English: "to get angry" },
    { Korean: "용서하다", English: "to forgive" },
    { Korean: "사과하다", English: "to apologize" },
    { Korean: "감사하다", English: "to thank" },
    { Korean: "축하하다", English: "to congratulate" },
    { Korean: "노래하다", English: "to sing" },
    { Korean: "춤추다", English: "to dance" },
    { Korean: "그리다", English: "to draw" },
    { Korean: "만들다", English: "to make" },
    { Korean: "고치다", English: "to fix" },
    { Korean: "청소하다", English: "to clean" },
    { Korean: "요리하다", English: "to cook" },
    { Korean: "빨래하다", English: "to do laundry" },
    { Korean: "운전하다", English: "to drive" },
    { Korean: "여행하다", English: "to travel" },
    { Korean: "운동하다", English: "to exercise" },
    { Korean: "공부하다", English: "to study" },
    { Korean: "일하다", English: "to work" },
    { Korean: "쉬다", English: "to rest" },
    { Korean: "잠자다", English: "to sleep" },
    { Korean: "꿈꾸다", English: "to dream" },
    { Korean: "믿다", English: "to believe" },
    { Korean: "바라다", English: "to hope/wish" },
    { Korean: "걱정하다", English: "to worry" },
    { Korean: "기뻐하다", English: "to rejoice" },
    { Korean: "슬퍼하다", English: "to be sad" },
    { Korean: "놀라다", English: "to be surprised" },
    { Korean: "무서워하다", English: "to be afraid" },
    { Korean: "부러워하다", English: "to envy" },
    { Korean: "질투하다", English: "to be jealous" },
    { Korean: "존경하다", English: "to respect" },
    { Korean: "무시하다", English: "to ignore" }
];

// 4. [Travel] Survival Travel Korean (20 sentences - unchanged)
const travel_korean = [
    { Korean: "여권 보여주세요.", English: "Please show me your passport." },
    { Korean: "체크인 부탁합니다.", English: "Check-in, please." },
    { Korean: "예약했습니다.", English: "I made a reservation." },
    { Korean: "방이 추워요.", English: "The room is cold." },
    { Korean: "와이파이 비밀번호가 뭐예요?", English: "What is the Wi-Fi password?" },
    { Korean: "여기 맛집 추천해주세요.", English: "Global restaurant recommendation please." },
    { Korean: "메뉴판 주세요.", English: "Menu please." },
    { Korean: "물 좀 주세요.", English: "Water please." },
    { Korean: "계산서 주세요.", English: "Bill please." },
    { Korean: "여기서 제일 인기 있는 게 뭐예요?", English: "What is the most popular dish here?" },
    { Korean: "덜 맵게 해주세요.", English: "Make it less spicy please." },
    { Korean: "이거 환불 되나요?", English: "Can I get a refund for this?" },
    { Korean: "깎아주세요.", English: "Please give me a discount." },
    { Korean: "입어봐도 되나요?", English: "Can I try this on?" },
    { Korean: "지하철 역이 어디예요?", English: "Where is the subway station?" },
    { Korean: "택시 불러주세요.", English: "Please call a taxi." },
    { Korean: "서울역으로 가주세요.", English: "To Seoul Station, please." },
    { Korean: "얼마나 걸려요?", English: "How long does it take?" },
    { Korean: "사진 좀 찍어주실래요?", English: "Could you take a picture for us?" },
    { Korean: "길을 잃었어요.", English: "I'm lost." }
];

function createExcel(data, filename) {
    const ws = xlsx.utils.json_to_sheet(data);
    const wb = xlsx.utils.book_new();
    xlsx.utils.book_append_sheet(wb, ws, "Sheet1");
    // Ensure the output file is written to the assets/files/samples directory
    xlsx.writeFile(wb, `../assets/files/samples/${filename}`);
    console.log(`Created ${filename}`);
}

createExcel(basic_korean, "basic_korean.xlsx");
createExcel(business_korean, "business_korean.xlsx");
createExcel(verbs_100, "korean_verbs_100.xlsx");
createExcel(travel_korean, "travel_korean.xlsx");
