const xlsx = require('xlsx');

// 1. [Basic] Daily Life Expressions (100 sentences)
const basic_korean = [
    { Korean: "안녕하세요.", English: "Hello." },
    { Korean: "처음 뵙겠습니다.", English: "Nice to meet you." },
    { Korean: "오랜만이에요.", English: "Long time no see." },
    { Korean: "어떻게 지내세요?", English: "How are you doing?" },
    { Korean: "잘 지내요.", English: "I'm doing well." },
    { Korean: "만나서 반가워요.", English: "Glad to meet you." },
    { Korean: "감사합니다.", English: "Thank you." },
    { Korean: "천만에요.", English: "You're welcome." },
    { Korean: "죄송합니다.", English: "I'm sorry." },
    { Korean: "괜찮아요.", English: "It's okay." },
    { Korean: "실례합니다.", English: "Excuse me." },
    { Korean: "잠시만요.", English: "Just a moment." },
    { Korean: "저기요.", English: "Excuse me (to call someone)." },
    { Korean: "네.", English: "Yes." },
    { Korean: "아니요.", English: "No." },
    { Korean: "아마도요.", English: "Maybe." },
    { Korean: "물론이죠.", English: "Of course." },
    { Korean: "부탁합니다.", English: "Please." },
    { Korean: "도와주세요.", English: "Help me." },
    { Korean: "이해했어요.", English: "I understand." },
    { Korean: "이해 못 했어요.", English: "I don't understand." },
    { Korean: "다시 말해주세요.", English: "Please say it again." },
    { Korean: "천천히 말해주세요.", English: "Please speak slowly." },
    { Korean: "영어 할 수 있어요?", English: "Can you speak English?" },
    { Korean: "한국어 조금 해요.", English: "I speak a little Korean." },
    { Korean: "이름이 뭐예요?", English: "What is your name?" },
    { Korean: "제 이름은 ...입니다.", English: "My name is ..." },
    { Korean: "어디서 오셨어요?", English: "Where are you from?" },
    { Korean: "저는 미국에서 왔어요.", English: "I am from the USA." },
    { Korean: "몇 살이세요?", English: "How old are you?" },
    { Korean: "직업이 뭐예요?", English: "What is your job?" },
    { Korean: "학생이에요.", English: "I am a student." },
    { Korean: "회사원이에요.", English: "I am an office worker." },
    { Korean: "취미가 뭐예요?", English: "What are your hobbies?" },
    { Korean: "저는 영화 보는 걸 좋아해요.", English: "I like watching movies." },
    { Korean: "오늘 날씨가 좋네요.", English: "The weather is good today." },
    { Korean: "비가 오네요.", English: "It's raining." },
    { Korean: "추워요.", English: "It's cold." },
    { Korean: "더워요.", English: "It's hot." },
    { Korean: "지금 몇 시예요?", English: "What time is it now?" },
    { Korean: "배고파요.", English: "I'm hungry." },
    { Korean: "배불러요.", English: "I'm full." },
    { Korean: "목 말라요.", English: "I'm thirsty." },
    { Korean: "맛있어요.", English: "It's delicious." },
    { Korean: "맛없어요.", English: "It's not delicious." },
    { Korean: "잘 먹겠습니다.", English: "I will eat well (Bon appétit)." },
    { Korean: "잘 먹었습니다.", English: "I ate well (Thank you for the meal)." },
    { Korean: "메뉴판 주세요.", English: "Menu please." },
    { Korean: "이거 주세요.", English: "This one please." },
    { Korean: "물 좀 주세요.", English: "Water please." },
    { Korean: "계산해 주세요.", English: "Check please." },
    { Korean: "영수증 주세요.", English: "Receipt please." },
    { Korean: "화장실이 어디예요?", English: "Where is the bathroom?" },
    { Korean: "입구는 어디예요?", English: "Where is the entrance?" },
    { Korean: "출구는 어디예요?", English: "Where is the exit?" },
    { Korean: "왼쪽으로 가세요.", English: "Go left." },
    { Korean: "오른쪽으로 가세요.", English: "Go right." },
    { Korean: "쭉 가세요.", English: "Go straight." },
    { Korean: "여기서 세워주세요.", English: "Stop here please." },
    { Korean: "얼마예요?", English: "How much is it?" },
    { Korean: "너무 비싸요.", English: "It's too expensive." },
    { Korean: "깎아주세요.", English: "Please give me a discount." },
    { Korean: "카드로 계산할게요.", English: "I will pay by card." },
    { Korean: "현금으로 계산할게요.", English: "I will pay by cash." },
    { Korean: "환불해 주세요.", English: "Please refund it." },
    { Korean: "교환해 주세요.", English: "Please exchange it." },
    { Korean: "이거 입어봐도 되나요?", English: "Can I try this on?" },
    { Korean: "사이즈가 안 맞아요.", English: "The size doesn't fit." },
    { Korean: "더 큰 사이즈 있어요?", English: "Do you have a bigger size?" },
    { Korean: "더 작은 사이즈 있어요?", English: "Do you have a smaller size?" },
    { Korean: "어떤 색깔 좋아해요?", English: "What color do you like?" },
    { Korean: "파란색 좋아해요.", English: "I like blue." },
    { Korean: "생일 축하해요.", English: "Happy birthday." },
    { Korean: "축하해요!", English: "Congratulations!" },
    { Korean: "새해 복 많이 받으세요.", English: "Happy New Year." },
    { Korean: "메리 크리스마스.", English: "Merry Christmas." },
    { Korean: "사랑해요.", English: "I love you." },
    { Korean: "보고 싶어요.", English: "I miss you." },
    { Korean: "좋아해요.", English: "I like you." },
    { Korean: "결혼해 줄래?", English: "Will you marry me?" },
    { Korean: "헤어지자.", English: "Let's break up." },
    { Korean: "정말요?", English: "Really?" },
    { Korean: "거짓말 하지 마세요.", English: "Don't lie." },
    { Korean: "약속해요.", English: "I promise." },
    { Korean: "비밀이에요.", English: "It's a secret." },
    { Korean: "걱정하지 마세요.", English: "Don't worry." },
    { Korean: "힘내세요.", English: "Cheer up." },
    { Korean: "수고하셨습니다.", English: "Good job." },
    { Korean: "피곤해요.", English: "I'm tired." },
    { Korean: "아파요.", English: "I'm sick/It hurts." },
    { Korean: "병원에 가야 해요.", English: "I need to go to the hospital." },
    { Korean: "약국이 어디예요?", English: "Where is the pharmacy?" },
    { Korean: "머리가 아파요.", English: "I have a headache." },
    { Korean: "배가 아파요.", English: "I have a stomachache." },
    { Korean: "감기 걸렸어요.", English: "I caught a cold." },
    { Korean: "조심하세요.", English: "Be careful." },
    { Korean: "위험해요.", English: "It's dangerous." },
    { Korean: "도와드릴까요?", English: "Can I help you?" },
    { Korean: "무슨 일이에요?", English: "What happened?" },
    { Korean: "재미있어요.", English: "It's fun." }
];

// 2. [Intermediate] Office Business Talk (100 sentences)
const business_korean = [
    { Korean: "안녕하세요. 이메일 잘 받았습니다.", English: "Hello. I received your email." },
    { Korean: "회의 일정은 언제인가요?", English: "When is the meeting schedule?" },
    { Korean: "보고서는 내일까지 제출해주세요.", English: "Please submit the report by tomorrow." },
    { Korean: "결재를 부탁드립니다.", English: "Please approve this." },
    { Korean: "이번 프로젝트의 목표는 무엇인가요?", English: "What is the goal of this project?" },
    { Korean: "예산안을 검토해주세요.", English: "Please review the budget proposal." },
    { Korean: "다음 주 출장 예정입니다.", English: "I am scheduled for a business trip next week." },
    { Korean: "회의실 예약했습니다.", English: "I booked a meeting room." },
    { Korean: "잠시 통화 가능하신가요?", English: "Are you available for a call?" },
    { Korean: "지금은 회의 중입니다.", English: "I am in a meeting right now." },
    { Korean: "나중에 다시 연락드리겠습니다.", English: "I will contact you later." },
    { Korean: "담당자 연결해 드리겠습니다.", English: "I will connect you to the person in charge." },
    { Korean: "협조해주셔서 감사합니다.", English: "Thank you for your cooperation." },
    { Korean: "문의사항이 있으시면 연락주세요.", English: "Please contact me if you have any questions." },
    { Korean: "첨부 파일을 확인해주세요.", English: "Please check the attached file." },
    { Korean: "빠른 회신 부탁드립니다.", English: "Please reply as soon as possible." },
    { Korean: "거래처 미팅이 잡혔습니다.", English: "A meeting with the client is scheduled." },
    { Korean: "계약서 초안을 보냈습니다.", English: "I sent the draft of the contract." },
    { Korean: "수정 사항이 있습니다.", English: "There are some revisions." },
    { Korean: "승인되었습니다.", English: "It has been approved." },
    { Korean: "반려되었습니다.", English: "It has been rejected." },
    { Korean: "추가 정보가 필요합니다.", English: "More information is needed." },
    { Korean: "일정을 변경해야 할 것 같습니다.", English: "I think we need to reschedule." },
    { Korean: "마감 기한을 지켜주세요.", English: "Please meet the deadline." },
    { Korean: "진행 상황을 공유해주세요.", English: "Please share the progress." },
    { Korean: "문제가 발생했습니다.", English: "A problem has occurred." },
    { Korean: "해결 방안을 모색 중입니다.", English: "We are looking for a solution." },
    { Korean: "성공적으로 완료되었습니다.", English: "It has been successfully completed." },
    { Korean: "실적 보고회가 있습니다.", English: "There is a performance report meeting." },
    { Korean: "야근을 해야 합니다.", English: "I have to work overtime." },
    { Korean: "주말 근무는 없습니다.", English: "There is no weekend work." },
    { Korean: "연차 휴가를 신청합니다.", English: "I apply for annual leave." },
    { Korean: "병가를 냈습니다.", English: "I took sick leave." },
    { Korean: "조퇴하겠습니다.", English: "I will leave early." },
    { Korean: "지각해서 죄송합니다.", English: "I am sorry for being late." },
    { Korean: "출근했습니다.", English: "I have arrived at work." },
    { Korean: "퇴근하겠습니다.", English: "I am leaving work." },
    { Korean: "점심 식사 맛있게 하세요.", English: "Enjoy your lunch." },
    { Korean: "오늘 회식 참석하시나요?", English: "Are you attending the company dinner today?" },
    { Korean: "명함 좀 주시겠습니까?", English: "Could you give me your business card?" },
    { Korean: "제 명함입니다.", English: "Here is my business card." },
    { Korean: "소개해 드리겠습니다.", English: "Let me introduce you." },
    { Korean: "우리 팀장님입니다.", English: "This is our team leader." },
    { Korean: "신입 사원입니다.", English: "This is a new employee." },
    { Korean: "인수인계 중입니다.", English: "I am in the middle of handover." },
    { Korean: "업무 분장이 필요합니다.", English: "Division of duties is needed." },
    { Korean: "효율성을 높여야 합니다.", English: "We need to increase efficiency." },
    { Korean: "비용을 절감해야 합니다.", English: "We need to cut costs." },
    { Korean: "고객 만족도가 중요합니다.", English: "Customer satisfaction is important." },
    { Korean: "시장 조사를 했습니다.", English: "We conducted market research." },
    { Korean: "경쟁사를 분석했습니다.", English: "We analyzed competitors." },
    { Korean: "전략을 세웠습니다.", English: "We established a strategy." },
    { Korean: "목표를 달성했습니다.", English: "We achieved the goal." },
    { Korean: "성과급이 지급됩니다.", English: "Performance bonuses will be paid." },
    { Korean: "승진을 축하합니다.", English: "Congratulations on your promotion." },
    { Korean: "퇴사하게 되었습니다.", English: "I am resigning." },
    { Korean: "그동안 감사했습니다.", English: "Thank you for everything." },
    { Korean: "송별회가 있습니다.", English: "There is a farewell party." },
    { Korean: "환영회가 있습니다.", English: "There is a welcome party." },
    { Korean: "워크숍을 갑니다.", English: "We are going to a workshop." },
    { Korean: "세미나에 참석합니다.", English: "I am attending a seminar." },
    { Korean: "교육을 받습니다.", English: "I am receiving training." },
    { Korean: "자격증을 취득했습니다.", English: "I obtained a certification." },
    { Korean: "외국어 능력이 필요합니다.", English: "Foreign language skills are required." },
    { Korean: "프레젠테이션을 잘했습니다.", English: "You did a good job on the presentation." },
    { Korean: "질문 있습니까?", English: "Do you have any questions?" },
    { Korean: "이해가 되시나요?", English: "Do you understand?" },
    { Korean: "다시 설명해 드리겠습니다.", English: "I will explain it again." },
    { Korean: "요점을 정리해주세요.", English: "Please summarize the main points." },
    { Korean: "회의록을 작성해주세요.", English: "Please write the meeting minutes." },
    { Korean: "아이디어가 좋습니다.", English: "That's a good idea." },
    { Korean: "다른 의견 있습니까?", English: "Any other opinions?" },
    { Korean: "만장일치로 통과되었습니다.", English: "It was passed unanimously." },
    { Korean: "반대 의견이 있습니다.", English: "There is a dissenting opinion." },
    { Korean: "절충안을 찾읍시다.", English: "Let's find a compromise." },
    { Korean: "결론을 내립시다.", English: "Let's draw a conclusion." },
    { Korean: "다음 안건으로 넘어갑시다.", English: "Let's move on to the next item." },
    { Korean: "시간이 부족합니다.", English: "We are running out of time." },
    { Korean: "잠시 쉬었다 합시다.", English: "Let's take a short break." },
    { Korean: "오늘 회의는 여기까지입니다.", English: "That's all for today's meeting." },
    { Korean: "수고 많으셨습니다.", English: "Thank you for your hard work." },
    { Korean: "좋은 주말 보내세요.", English: "Have a good weekend." },
    { Korean: "월요일에 뵙겠습니다.", English: "See you on Monday." },
    { Korean: "복사가 안 됩니다.", English: "The copier is not working." },
    { Korean: "프린터 용지가 없습니다.", English: "The printer is out of paper." },
    { Korean: "인터넷이 느립니다.", English: "The internet is slow." },
    { Korean: "서버가 다운되었습니다.", English: "The server is down." },
    { Korean: "보안이 중요합니다.", English: "Security is important." },
    { Korean: "비밀번호를 변경하세요.", English: "Please change your password." },
    { Korean: "로그인이 안 됩니다.", English: "I can't log in." },
    { Korean: "IT 팀에 문의하세요.", English: "Please contact the IT team." },
    { Korean: "탕비실에 커피가 없습니다.", English: "There is no coffee in the pantry." },
    { Korean: "에어컨이 너무 춥습니다.", English: "The air conditioner is too cold." },
    { Korean: "히터 좀 틀어주세요.", English: "Please turn on the heater." },
    { Korean: "창문 좀 열어주세요.", English: "Please open the window." },
    { Korean: "청소 업체 불라주세요.", English: "Please call the cleaning service." },
    { Korean: "택배가 도착했습니다.", English: "A package has arrived." },
    { Korean: "우편물 확인해주세요.", English: "Please check the mail." },
    { Korean: "주차권 필요하세요?", English: "Do you need a parking ticket?" },
    { Korean: "엘리베이터가 고장났습니다.", English: "The elevator is broken." }
];

// 4. [Travel] Survival Travel Korean (100 sentences)
const travel_korean = [
    { Korean: "여권 보여주세요.", English: "Please show me your passport." },
    { Korean: "체크인 부탁합니다.", English: "Check-in, please." },
    { Korean: "예약했습니다.", English: "I made a reservation." },
    { Korean: "방이 추워요.", English: "The room is cold." },
    { Korean: "와이파이 비밀번호가 뭐예요?", English: "What is the Wi-Fi password?" },
    { Korean: "여기 맛집 추천해주세요.", English: "Global restaurant recommendation please." },
    { Korean: "메뉴판 주세요.", English: "Menu please." },
    { Korean: "물 좀 주세요.", English: "Water please." },
    { Korean: "계산서 주세요.", English: "Bill please." },
    { Korean: "여기서 제일 인기 있는 게 뭐예요?", English: "What is the most popular dish here?" },
    { Korean: "덜 맵게 해주세요.", English: "Make it less spicy please." },
    { Korean: "이거 환불 되나요?", English: "Can I get a refund for this?" },
    { Korean: "깎아주세요.", English: "Please give me a discount." },
    { Korean: "입어봐도 되나요?", English: "Can I try this on?" },
    { Korean: "지하철 역이 어디예요?", English: "Where is the subway station?" },
    { Korean: "택시 불러주세요.", English: "Please call a taxi." },
    { Korean: "서울역으로 가주세요.", English: "To Seoul Station, please." },
    { Korean: "얼마나 걸려요?", English: "How long does it take?" },
    { Korean: "사진 좀 찍어주실래요?", English: "Could you take a picture for us?" },
    { Korean: "길을 잃었어요.", English: "I'm lost." },
    { Korean: "도와주세요.", English: "Help me." },
    { Korean: "경찰을 불러주세요.", English: "Please call the police." },
    { Korean: "병원에 가고 싶어요.", English: "I want to go to the hospital." },
    { Korean: "약국이 어디 있나요?", English: "Where is the pharmacy?" },
    { Korean: "화장실이 급해요.", English: "I need to use the bathroom urgently." },
    { Korean: "가방을 잃어버렸어요.", English: "I lost my bag." },
    { Korean: "지갑을 잃어버렸어요.", English: "I lost my wallet." },
    { Korean: "여권을 잃어버렸어요.", English: "I lost my passport." },
    { Korean: "대사관이 어디예요?", English: "Where is the embassy?" },
    { Korean: "환전소는 어디예요?", English: "Where is the currency exchange?" },
    { Korean: "ATM이 어디예요?", English: "Where is the ATM?" },
    { Korean: "신용카드 되나요?", English: "Do you accept credit cards?" },
    { Korean: "현금만 받나요?", English: "Do you only accept cash?" },
    { Korean: "잔돈은 괜찮아요.", English: "Keep the change." },
    { Korean: "팁 포함인가요?", English: "Is tip included?" },
    { Korean: "포장해 주세요.", English: "To-go, please." },
    { Korean: "따로 계산할게요.", English: "We will pay separately." },
    { Korean: "젓가락 주세요.", English: "Chopsticks please." },
    { Korean: "포크 주세요.", English: "Fork please." },
    { Korean: "냅킨 주세요.", English: "Napkin please." },
    { Korean: "리필 되나요?", English: "Is refill free?" },
    { Korean: "너무 맛있어요.", English: "It's very delicious." },
    { Korean: "짜요.", English: "It's salty." },
    { Korean: "싱거워요.", English: "It's bland." },
    { Korean: "달아요.", English: "It's sweet." },
    { Korean: "매워요.", English: "It's spicy." },
    { Korean: "셔요.", English: "It's sour." },
    { Korean: "써요.", English: "It's bitter." },
    { Korean: "알러지가 있어요.", English: "I have an allergy." },
    { Korean: "고기는 빼주세요.", English: "Please remove meat." },
    { Korean: "채식주의자용 메뉴 있나요?", English: "Do you have vegetarian menu?" },
    { Korean: "돼지고기 못 먹어요.", English: "I can't eat pork." },
    { Korean: "소고기 못 먹어요.", English: "I can't eat beef." },
    { Korean: "해산물 못 먹어요.", English: "I can't eat seafood." },
    { Korean: "견과류 알러지 있어요.", English: "I have nut allergy." },
    { Korean: "빈 방 있나요?", English: "Do you have vacant rooms?" },
    { Korean: "1박에 얼마예요?", English: "How much per night?" },
    { Korean: "조식 포함인가요?", English: "Is breakfast included?" },
    { Korean: "체크아웃 시간은 언제예요?", English: "When is check-out time?" },
    { Korean: "짐 맡길 수 있나요?", English: "Can I leave my luggage?" },
    { Korean: "택시 잡아주세요.", English: "Please catch a taxi." },
    { Korean: "공항 버스 어디서 타요?", English: "Where can I take the airport bus?" },
    { Korean: "기차역이 어디예요?", English: "Where is the train station?" },
    { Korean: "버스 정류장이 어디예요?", English: "Where is the bus stop?" },
    { Korean: "이 버스 시청 가나요?", English: "Does this bus go to City Hall?" },
    { Korean: "내려주세요.", English: "Please let me off." },
    { Korean: "환승해야 하나요?", English: "Do I need to transfer?" },
    { Korean: "몇 호선 타야 해요?", English: "Which line should I take?" },
    { Korean: "오른쪽.", English: "Right." },
    { Korean: "왼쪽.", English: "Left." },
    { Korean: "직진.", English: "Straight." },
    { Korean: "건너편.", English: "Across the street." },
    { Korean: "근처에 편의점 있나요?", English: "Is there a convenience store nearby?" },
    { Korean: "슈퍼마켓 어디예요?", English: "Where is the supermarket?" },
    { Korean: "기념품 가게 어디예요?", English: "Where is the souvenir shop?" },
    { Korean: "면세점 어디예요?", English: "Where is the duty-free shop?" },
    { Korean: "세일 중인가요?", English: "Is it on sale?" },
    { Korean: "영업시간이 어떻게 되나요?", English: "What are the business hours?" },
    { Korean: "문 닫았나요?", English: "Is it closed?" },
    { Korean: "언제 여나요?", English: "When does it open?" },
    { Korean: "입장료 얼마예요?", English: "How much is the admission fee?" },
    { Korean: "사진 찍어도 되나요?", English: "Can I take pictures?" },
    { Korean: "플래시 터트려도 되나요?", English: "Can I use flash?" },
    { Korean: "한국어 가이드 있나요?", English: "Is there a Korean guide?" },
    { Korean: "오디오 가이드 있나요?", English: "Is there an audio guide?" },
    { Korean: "지도 있나요?", English: "Do you have a map?" },
    { Korean: "추천 코스 있나요?", English: "Any recommended course?" },
    { Korean: "걸어서 갈 수 있나요?", English: "Can I go on foot?" },
    { Korean: "너무 멀어요.", English: "It's too far." },
    { Korean: "가까워요.", English: "It's close." },
    { Korean: "전화기 빌릴 수 있을까요?", English: "Can I borrow a phone?" },
    { Korean: "충전기 빌릴 수 있을까요?", English: "Can I borrow a charger?" },
    { Korean: "콘센트 어디 있나요?", English: "Where is the outlet?" },
    { Korean: "비상구는 어디인가요?", English: "Where is the emergency exit?" },
    { Korean: "소화기는 어디 있나요?", English: "Where is the fire extinguisher?" },
    { Korean: "구급차 불러주세요.", English: "Call an ambulance." }
];

function createExcel(data, filename) {
    const ws = xlsx.utils.json_to_sheet(data);
    const wb = xlsx.utils.book_new();
    xlsx.utils.book_append_sheet(wb, ws, "Sheet1");
    // Ensure the output file is written to the assets/files/samples directory
    xlsx.writeFile(wb, `../assets/files/samples/${filename}`);
    console.log(`Created ${filename}`);
}

createExcel(basic_korean, "basic_korean.xlsx");
createExcel(business_korean, "business_korean.xlsx");
createExcel(travel_korean, "travel_korean.xlsx");
